In [13]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

## Using dropout

In [14]:
# defining dropout instance
prob = .5

dropout = nn.Dropout(p=prob)
x = torch.ones(10)

y = dropout(x)
print(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([2., 2., 2., 0., 2., 2., 2., 2., 0., 2.])
tensor(1.6000)


In [15]:
dropout.eval()
y = dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [16]:
# Note: F.dropout() is not deactivated in eval mode: you should manually switch it off
# dropout.eval() does not work does'nt work
y = F.dropout(x, training=False)

print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [17]:
dropout.eval()
y = dropout(x)
print(y)

dropout.train()
y = dropout(x)
print(y)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([2., 2., 2., 2., 0., 2., 0., 2., 0., 0.])
