In [9]:
import numpy as np
import torch
import torch.nn as nn

In [10]:
# build two model

wideNet = nn.Sequential(
    nn.Linear(2,4),
    nn.Linear(4,3)
)


deepNet = nn.Sequential(
    nn.Linear(2,2),
    nn.Linear(2,2),
    nn.Linear(2,3),
)

# printing to have a look 
print(wideNet,end="\n\n")
print(deepNet,end="\n\n")

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)

Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)



## Peeking inside the network

In [11]:
# check out the parameters
for p in deepNet.named_parameters():
    print(p,end='\n\n')

('0.weight', Parameter containing:
tensor([[-0.0581, -0.5791],
        [ 0.3967, -0.5903]], requires_grad=True))

('0.bias', Parameter containing:
tensor([0.5276, 0.6130], requires_grad=True))

('1.weight', Parameter containing:
tensor([[-0.5779, -0.3551],
        [ 0.1011, -0.6826]], requires_grad=True))

('1.bias', Parameter containing:
tensor([-0.0955, -0.6191], requires_grad=True))

('2.weight', Parameter containing:
tensor([[-0.5981,  0.6149],
        [ 0.4628, -0.1626],
        [ 0.4397, -0.6009]], requires_grad=True))

('2.bias', Parameter containing:
tensor([0.0370, 0.4184, 0.1086], requires_grad=True))



In [12]:
# count the total number of nodes ( = the number od biases ) 

# named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesWide = 0
for p in wideNet.named_parameters():
    if "bias" in p[0]:
        numNodesWide += len(p[1])
        
numNodesDeep = 0
for paramName,paramVect in deepNet.named_parameters():
    if "bias" in paramName:
        numNodesDeep += len(paramVect)
        
print("There are %s nodes in the wide network" % numNodesWide)
print("There are %s nodes in the deep network" % numNodesDeep)

There are 7 nodes in the wide network
There are 7 nodes in the deep network


In [13]:
# just the parameters , without names
for p in wideNet.parameters():
    print(p)
    print(' ')

Parameter containing:
tensor([[-0.1667,  0.4618],
        [ 0.0966,  0.6079],
        [ 0.1724, -0.4797],
        [-0.4513, -0.3306]], requires_grad=True)
 
Parameter containing:
tensor([ 0.6234, -0.2336, -0.6798, -0.2385], requires_grad=True)
 
Parameter containing:
tensor([[ 0.0063,  0.4285, -0.1742, -0.3618],
        [-0.0969, -0.2059, -0.3802, -0.3264],
        [ 0.2195, -0.4522, -0.3330,  0.2360]], requires_grad=True)
 
Parameter containing:
tensor([-0.3692, -0.0514, -0.2248], requires_grad=True)
 


In [14]:
# total count of trainable parameters
nParams = 0
for p in wideNet.parameters():
    if p.requires_grad:
        print("This piece has %s parameters." %p.numel())
        nParams += p.numel()
print("\n\n There are %s total parameters." % nParams)

This piece has 8 parameters.
This piece has 4 parameters.
This piece has 12 parameters.
This piece has 3 parameters.


 There are 27 total parameters.


In [15]:
# using list comprehension

nParams = np.sum([p.numel() for p in wideNet.parameters() if p.requires_grad])
print("Widenet has %s total parameters." % nParams)

nParams2 = np.sum([p.numel() for p in deepNet.parameters() if p.requires_grad])
print("DeepNet has %s total parameters." % nParams2)

Widenet has 27 total parameters.
DeepNet has 21 total parameters.


In [19]:
# simple way to print 
from torchinfo import summary
summary(wideNet,(1, 2))

Layer (type:depth-idx)                   Output Shape              Param #
Sequential                               [1, 3]                    --
├─Linear: 1-1                            [1, 4]                    12
├─Linear: 1-2                            [1, 3]                    15
Total params: 27
Trainable params: 27
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00